name: smartfit
description: Smart Fit Flutter App
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  introduction_screen: ^1.0.7
  bottom_navy_bar: ^5.3.2
  intl: ^0.16.1
  sqflite: ^1.2.1
  shared_preferences: ^0.5.6+2
  charts_flutter: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
  - images/
  - assets/
  - i18n/
  - fonts/